image: node:16.17.0

before_script:
  - npm config set registry https://registry.npmmirror.com
  - npm install -g pnpm

cache:
  paths:
    - node_modules

stages:
  - build

build_job:
  stage: build
  script:
    - pnpm run build
  artifacts:
    paths:
      - public
    expire_in: 1 week
