/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ['**/.*', '**/*.test.{ts,tsx}'],
  serverDependenciesToBundle: [
    'marked',
    /^remark.*/,
    /^rehype.*/,
    /^mdast.*/,
    /^micromark.*/,
    /^unist-util.*/,
    /^vfile.*/,
    /^character-entities.*/,
    /^hast-util.*/,
    /^mermaid.*/,
    'unified',
    'trough',
    'decode-named-character-reference',
    'zwitch',
    'bail',
    'is-plain-obj',
    'html-void-elements',
    'property-information',
    'stringify-entities',
    'ccount',
    'comma-separated-tokens',
    'space-separated-tokens',
    'devlop',
    'trim-lines',
    'lowlight',
    'longest-streak',
    'hastscript',
    'web-namespaces',
    'emoticon',
    'markdown-table',
    'github-slugger',
  ],
  serverModuleFormat: 'cjs',
  postcss: true,
  // appDirectory: 'app',
  // assetsBuildDirectory: 'public/build',
  // serverBuildPath: 'build/index.js',
  // publicPath: '/build/',
};
