name: Mirroring

on: [push, delete]

jobs:
  to_jihu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            https://${{ secrets.JIHU_USERNAME }}:${{ secrets.JIHU_ACCESS_TOKEN }}@jihulab.com/${{ secrets.JIHU_USERNAME }}/portfolio-remix.git

  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_ACCESS_TOKEN }}@git.slinvent.com:10443/${{ secrets.GITLAB_USERNAME }}/portfolio-remix.git
